### ISSUE TITLE
Failed to start docker application with rabbitMQ

### ISSUE THREAD

**Issue by tejashjl** [clamp-orchestrator/clamp-core#10]
ARAVIND: After changing the rabbit mq credentials, it isn’t working. I am getting 2020/08/13 16:53:38 [AMQP Consumer] : Failed to connect to RabbitMQ: dial tcp 127.0.0.1:5672: connect: connection refused. It is searching for rabbitmq within the container, which isn’t there.

**Comment by priyaaank** [comment]
This is irrelevant since we have moved to docker to run tests and to docker-compose to start a local setup. Will assume that this can be closed now.

**Comment by tejash-jl** [comment]
#12 will solve this ambiguity
