### ISSUE TITLE
Update clamp documentation

### ISSUE THREAD

**Issue by tejashjl** [clamp-orchestrator/clamp-core#8]
- [] Add link to project source code
- [] Instructions to configure PostgreSQL, RabbitMQ or Kafka in clamp
- [] Recheck the heading or add headings at certain blocks
- [] Provide a name for the container in docker run command
- [] Update email addresses to sahaj.ai in the contributing section

**Comment by priyaaank** [comment]
Since most of the items listed here have been addressed for the documentation microsite, I'll assume this can be closed successfully.
