### ISSUE TITLE
Update clamp config

### ISSUE THREAD

**Issue by tejashjl** [clamp-orchestrator/clamp-core#9]
- Specify the minimum set of required dependencies to start the application
- Add instructions in documentation about how to update the configurations and where to update it.
- Update configuration section with proper examples / default values (Kafka contains wrong default value / example)
- Add steps to configure clamp while running as a docker

**Comment by priyaaank** [comment]
The documentation has been added in the microsite now and all these details can be added in [clamp-orchestrator](https://github.com/clamp-orchestrator/clamp-orchestrator) repo now.
